- include: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Add /snap/bin to PATH
  lineinfile:
      dest={{ ansible_env.HOME }}/.localrc
      line='PATH=/snap/bin:$PATH'
      create=yes
