- include_tasks: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Add /snap/bin to PATH
  lineinfile:
      dest={{ ansible_env.HOME }}/.localrc
      line='echo "$PATH" | grep -q \'/snap/bin\' || PATH=/snap/bin:"$PATH"'
      create=yes
