- name: Create directories in HOME
  become: no
  with_items:
    - src
    - tmp
    - bin
  file: path={{ ansible_env.HOME }}/{{ item }} state=directory

- name: Create directory for lock file
  become: no
  file:
    path: '{{ ansible_env.HOME }}/run'
    state: directory
    mode: '0700'

- name: Add HOME/bin to $PATH
  become: no
  lineinfile:
    path: "{{ ansible_env.HOME }}/.localrc"
    line: 'echo "$PATH" | grep -q "$HOME/bin" || PATH="$HOME/bin:$PATH"'
    create: yes
