- include: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Deploy config files.
  become: no
  with_fileglob:
      - .screenrc*
  copy: src={{ item }} dest={{ ansible_env.HOME }}

- name: Deploy screen aliases
  become: no
  copy:
    src=src
    dest={{ ansible_env.HOME }}
    mode=0644

- name: Enable bash to call command sa and sb
  become: no
  with_items:
    - sa
    - sb
  lineinfile:
    dest={{ ansible_env.HOME }}/.local_bashrc
    line='. ~/src/{{ item }}'
    create=yes

- name: Specify the path to screen socket file
  become: no
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.localrc'
    line: 'env | grep -q "SCREENDIR" || export SCREENDIR="$HOME/run"'
