- name: Download debian gpg key
  uri:
    url: "https://download.docker.com/linux/{{ ansible_distribution.lower() }}/gpg"
    return_content: yes
  register: debian_gpg_key

- name: Import debian gpg key
  become: yes
  command:
    argv:
      - gpg
      - --dearmor
      - -o
      - /usr/share/keyrings/docker-archive-keyring.gpg
    stdin: "{{ debian_gpg_key.content }}"
