- include: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Add user to docker group
  become: yes
  user:
     user={{ ansible_env.USER }}
     groups=docker
     append=yes

- name: Deploy docker commands
  become: no
  copy:
    dest={{ ansible_env.HOME }}
    src=bin
    mode=0755
