- include: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Download rustup installer
  become: no
  get_url:
    dest={{ ansible_env.HOME }}/src/rustup-init.sh
    mode=0644
    url=https://sh.rustup.rs

- name: Install rustup
  become: no
  command: bash {{ ansible_env.HOME }}/src/rustup-init.sh -y
    creates={{ ansible_env.HOME }}/.cargo/env

- name: Enable zsh to use cargo
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.local_zshrc
      line='. ~/.cargo/env'
      create=yes

- name: Install rustfmt
  become: no
  command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/rustup component add rustfmt"
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustfmt"

- name: Install rust src
  become: no
  with_items:
    - stable
  command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/rustup component add rust-src --toolchain {{ item }}"
    creates: "{{ ansible_env.HOME }}/.rustup/toolchains/{{ item }}-x86_64-unknown-linux-gnu/lib/rustlib/src/rust"

- name: Install nightly toolchain for racer
  become: no
  command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/rustup toolchain install nightly"
    creates: "{{ ansible_env.HOME }}/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu"

- name: Install racer
  become: no
  with_items:
    - racer
  command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/cargo +nightly install {{ item }}"
    creates: "{{ ansible_env.HOME }}/.cargo/bin/{{ item }}"

- name: Deploy emacs setting file
  become: no
  copy:
      src=.emacs.d
      dest={{ ansible_env.HOME }}

- name: Make emacs load rust.el
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.emacs.d/loads.el
      line='(load "~/.emacs.d/init.d/rust")'
      create=yes
