- include: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Download rustup installer
  become: no
  get_url:
    dest={{ ansible_env.HOME }}/src/rustup-init.sh
    mode=0644
    url=https://sh.rustup.rs

- name: Install rustup
  become: no
  command: bash {{ ansible_env.HOME }}/src/rustup-init.sh -y
    creates={{ ansible_env.HOME }}/.cargo/env

- name: Enable zsh to use cargo
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.localrc
      line='. ~/.cargo/env'
      create=yes

- name: Specify web browser to read cargo doc for WSL
  become: no
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.localrc"
    line: "env | grep 'BROWSER' || export BROWSER='firefox'"
    create: yes

- name: Install rustfmt
  become: no
  command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/rustup component add rustfmt"
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustfmt"

- name: Install rust src
  become: no
  with_items:
    - stable
  command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/rustup component add rust-src --toolchain {{ item }}"
    creates: "{{ ansible_env.HOME }}/.rustup/toolchains/{{ item }}-x86_64-unknown-linux-gnu/lib/rustlib/src/rust"

- name: Deploy .cargo/config
  become: no
  copy:
    src=.cargo
    dest={{ ansible_env.HOME }}
