- include: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Download rustup installer
  become: no
  get_url:
    dest={{ ansible_env.HOME }}/bin/rustup-init.sh
    mode=0644
    url=https://sh.rustup.rs
  register: rust_installer

- name: Install rustup
  become: no
  command: bash {{ ansible_env.HOME }}/bin/rustup-init.sh -y
  when: rust_installer.changed

- name: Enable zsh use cargo
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.local_zshrc
      line='. ~/.cargo/env'
      create=yes

- name: Install rust tools
  become: no
  with_items:
      - rustfmt --toolchain stable-x86_64-unknown-linux-gnu
      - rust-src
  command: "{{ ansible_env.HOME }}/.cargo/bin/rustup component add {{ item }}"
  when: rust_installer.changed

- name: Install crates
  become: no
  with_items:
      - racer --version 2.0.14
  command: "{{ ansible_env.HOME }}/.cargo/bin/cargo install {{ item }}"
  when: rust_installer.changed

- name: Deploy emacs setting file
  become: no
  copy:
      src=.emacs.d
      dest={{ ansible_env.HOME }}

- name: Make emacs load rust.el
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.emacs.d/loads.el
      line='(load "~/.emacs.d/init.d/rust")'
      create=yes
