- name: Download gpg key
  become: no
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: "{{ ansible_env.HOME }}/src/hashicorp-archive-keyring.gpg"

- name: Import gpg key
  become: yes
  command:
    cmd: gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg "{{ ansible_env.HOME }}/src/hashicorp-archive-keyring.gpg"
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Deploy apt source list
  become: yes
  template:
    src: hashicorp.list.j2
    dest: /etc/apt/sources.list.d/hashicorp.list

- name: Install Packages
  become: yes
  apt:
    name: ['terraform']
    state: present
    cache_valid_time: 3600
    update_cache: yes
