- include_tasks: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Create.venv directory
  become: no
  file: path={{ ansible_env.HOME }}/.venv state=directory

- name: Install default packages for python3
  become: no
  pip:
    name: [
      'wheel',
      'ipython',
      'flake8',
      'autopep8',
      'autoflake',
      'black',
      'isort',
      'mypy',
      'doc8',
      'pytest'
      ]
    virtualenv_command: "python3 -m venv"
    virtualenv: "{{ ansible_env.HOME }}/.venv/python3"

- name: Set default virtualenv in .localrc
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.localrc
      line='test -z "$VIRTUAL_ENV" && . ~/.venv/python3/bin/activate'
      create=yes

- name: Enable pipenv in virtualenv
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.localrc
      line='alias pipenv="PIPENV_IGNORE_VIRTUALENVS=1 pipenv"'
      create=yes
