- include: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Deploy config files.
  become: no
  with_items:
      - .aliasrc
      - .zshrc
  copy: src={{ item }} dest={{ ansible_env.HOME }}
