- name: Download setup script
  become: no
  get_url:
    url: https://deb.nodesource.com/setup_{{ nodejs.version }}
    dest: "{{ ansible_env.HOME }}/src/setup_{{ nodejs.version }}"

- name: Run setup script
  become: yes
  command:
    bash {{ ansible_env.HOME }}/src/setup_{{ nodejs.version }}

- name: Install nodejs
  become: yes
  apt:
    name: nodejs
    state: present
    cache_valid_time: 3600
    update_cache: yes
