- include_tasks: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Deploy emacs config files
  become: no
  copy:
      src=.emacs.d
      dest={{ ansible_env.HOME }}

- name: Make sure to create directory ~/.config
  become: no
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Make emacs load languages.el
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.emacs.d/loads.el
      line='(load "~/.emacs.d/init.d/languages")'
      create=yes
