- name: Install build dependencies
  become: yes
  apt:
    name: ["build-essential", "curl", "libffi-dev", "libffi8", "libgmp-dev", "libgmp10", "libncurses-dev", "libncurses6", "libtinfo6"]
    state: present
    cache_valid_time: 3600
    update_cache: yes
