- include_tasks: debian_packages_ghcup.yml
  when: ansible_distribution == 'Debian'

- name: Download ghcup installer
  become: no
  get_url:
    url: https://get-ghcup.haskell.org
    dest: "{{ ansible_env.HOME }}/src/setup_ghcup"

- name: Run ghcup installer
  become: no
  environment:
    BOOTSTRAP_HASKELL_NONINTERACTIVE: 1
    BOOTSTRAP_HASKELL_GHC_VERSION: recommended
    BOOTSTRAP_HASKELL_CABAL_VERSION: recommended
    BOOTSTRAP_HASKELL_INSTALL_HLS: 1
  command:
    sh "{{ ansible_env.HOME }}/src/setup_ghcup"

- name: Add command path to $PATH
  become: no
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.localrc"
    line: source "{{ ansible_env.HOME }}/.ghcup/env"
    create: yes
