- include: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Set environment variable to treat .h files as cpp source code.
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.localrc
      line='export GTAGSFORCECPP='
      create=yes
