- include: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Deploy .shellrc
  become: no
  copy:
      dest={{ ansible_env.HOME }}/.shellrc
      src=.shellrc

- name: Include .shellrc
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.bashrc
      line='test -f "$HOME/.shellrc" && . "$HOME/.shellrc"'
      create=yes

- name: Include .local_bashrc
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.bashrc
      line='test -f "$HOME/.local_bashrc" && . "$HOME/.local_bashrc"'
      create=yes
