- include: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Deploy .shellrc
  become: no
  copy:
      dest={{ ansible_env.HOME }}/.shellrc
      src=.shellrc

- name: Include .shellrc, .localrc, and .local_bashrc
  become: no
  with_items:
    - .shellrc
    - .localrc
    - .local_bashrc
  lineinfile:
      dest={{ ansible_env.HOME }}/.bashrc
      line='test -f "$HOME/{{ item }}" && . "$HOME/{{ item }}"'
      create=yes
