- name: Download emacs source code
  become: no
  get_url:
    url: "https://ftp.jaist.ac.jp/pub/GNU/emacs/emacs-{{ emacs.version }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/src/emacs-{{ emacs.version }}.tar.gz"
    mode: 0444

- name: Unarchive emacs source code
  become: no
  unarchive:
    src: "{{ ansible_env.HOME }}/src/emacs-{{ emacs.version }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/src"
    remote_src: yes
    creates: "{{ ansible_env.HOME }}/src/emacs-{{ emacs.version }}"

- name: configure emacs
  become: no
  command:
    chdir: "{{ ansible_env.HOME }}/src/emacs-{{ emacs.version }}"
    argv:
      - ./configure
      - --without-x
    creates: "{{ ansible_env.HOME }}/src/emacs-{{ emacs.version }}/Makefile"

- name: build emacs
  become: no
  command:
    cmd: make
    chdir: "{{ ansible_env.HOME }}/src/emacs-{{ emacs.version }}"
    creates: /usr/local/bin/emacs

- name: Install emacs
  become: yes
  command:
    argv:
      - make
      - install
    chdir: "{{ ansible_env.HOME }}/src/emacs-{{ emacs.version }}"
    creates: /usr/local/bin/emacs
