- name: Install packages.
  become: yes
  apt:
    name:
      - build-essential
      - pkg-config
      - libgnutls28-dev
      - libtinfo-dev
      - texinfo
    state: present
    cache_valid_time: 3600
    update_cache: yes
