- include_tasks: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Deploy .emacs.d
  become: no
  with_items:
      - .emacs.d
  copy:
      src={{ item }}
      dest={{ ansible_env.HOME }}

- name: Load personal settings from init.el
  become: no
  with_items:
      - (load "~/.emacs.d/init.d/backup")
      - (load "~/.emacs.d/init.d/key-bind")
      - (load "~/.emacs.d/init.d/display")
      - (load "~/.emacs.d/init.d/daemon")
      - (load "~/.emacs.d/init.d/resize-window")
      - (load "~/.emacs.d/init.d/format")
  lineinfile:
      dest={{ ansible_env.HOME }}/.emacs.d/loads.el
      line={{ item }}
      create=yes

- name: Deploy aliases for emacsclient
  become: no
  copy:
      dest={{ ansible_env.HOME }}
      src=bin
      mode=0755
