- name: Install Packages.
  become: yes
  apt:
    name: [
      'gdb',
      'build-essential',
      'cppcheck',
      'clang',
      'glibc-doc',
      'cppman',
      'clang-format',
      'libclang-dev'
      ]
    state: present
    cache_valid_time: 3600
    update_cache: yes
