- include: debian_packages.yml
  when: ansible_os_family == 'Debian'

- name: Deploy emacs settinf file.
  become: no
  copy:
      src=.emacs.d
      dest={{ ansible_env.HOME }}

- name: Make emacs load cpp.el.
  become: no
  lineinfile:
      dest={{ ansible_env.HOME }}/.emacs.d/loads.el
      line='(load "~/.emacs.d/init.d/cpp")'
      create=yes
